#Requires -Modules ExchangeOnlineManagement

# Minimal PowerShell 5.1/7 compatible Copilot audit export script
# This template is generated by the Purview Audit eXporter (PAX) app

param(
    [Parameter(Mandatory = $false)]
    [switch]$InHelper
)

# Hard-coded configuration values will be injected here by the app
# Template variables: {{START_DATE}}, {{END_DATE}}, {{AUTH_MODE}}, {{ACTIVITIES}}, {{OUTPUT_FILE}}, etc.

# Simple authentication function
function Connect-ToPurview {
    param([string]$AuthMode = "WebLogin")
    
    Write-Host "Connecting to Microsoft Purview..." -ForegroundColor Green
    
    try {
        if ($AuthMode -eq "WebLogin") {
            Connect-ExchangeOnline -ShowBanner:$false
        } elseif ($AuthMode -eq "DeviceCode") {
            Connect-ExchangeOnline -Device -ShowBanner:$false
        } else {
            Connect-ExchangeOnline -ShowBanner:$false
        }
        Write-Host "Successfully connected to Purview audit logs" -ForegroundColor Green
        return $true
    } catch {
        Write-Host "Failed to connect: $($_.Exception.Message)" -ForegroundColor Red
        return $false
    }
}

# Simple audit log search function
function Search-AuditLogs {
    param(
        [string]$StartDate,
        [string]$EndDate,
        [string[]]$ActivityTypes,
        [int]$ResultSize = 5000
    )
    
    Write-Host "Searching audit logs from $StartDate to $EndDate..." -ForegroundColor Cyan
    Write-Host "Activity types: $($ActivityTypes -join ', ')" -ForegroundColor Cyan
    
    $allResults = @()
    $currentStart = [datetime]$StartDate
    $finalEnd = [datetime]$EndDate
    
    while ($currentStart -lt $finalEnd) {
        $currentEnd = $currentStart.AddHours(8)
        if ($currentEnd -gt $finalEnd) { $currentEnd = $finalEnd }
        
        Write-Host "Querying: $($currentStart.ToString('yyyy-MM-dd HH:mm')) to $($currentEnd.ToString('yyyy-MM-dd HH:mm'))" -ForegroundColor Yellow
        
        try {
            $results = Search-UnifiedAuditLog -StartDate $currentStart -EndDate $currentEnd -Operations $ActivityTypes -ResultSize $ResultSize
            if ($results) {
                $allResults += $results
                Write-Host "Found $($results.Count) records in this time window" -ForegroundColor Green
            } else {
                Write-Host "No records found in this time window" -ForegroundColor Gray
            }
        } catch {
            Write-Host "Error searching time window: $($_.Exception.Message)" -ForegroundColor Red
        }
        
        $currentStart = $currentEnd
        Start-Sleep -Milliseconds 100  # Brief pause to avoid throttling
    }
    
    return $allResults
}

# Simple CSV export function
function Export-ToCsv {
    param(
        [array]$Results,
        [string]$OutputPath
    )
    
    if (-not $Results -or $Results.Count -eq 0) {
        Write-Host "No results to export" -ForegroundColor Yellow
        return
    }
    
    Write-Host "Exporting $($Results.Count) records to CSV..." -ForegroundColor Cyan
    
    $exportData = @()
    foreach ($result in $Results) {
        try {
            $auditData = if ($result.AuditData) { $result.AuditData | ConvertFrom-Json } else { $null }
            
            $exportData += [PSCustomObject]@{
                RecordType = $result.RecordType
                CreationDate = $result.CreationDate
                UserIds = $result.UserIds
                Operations = $result.Operations
                AuditData = $result.AuditData
                ResultIndex = $result.ResultIndex
                ResultCount = $result.ResultCount
                Identity = $result.Identity
                IsValid = $result.IsValid
                ObjectState = $result.ObjectState
                # Additional fields from AuditData if available
                UserId = if ($auditData) { $auditData.UserId } else { $null }
                ClientIP = if ($auditData) { $auditData.ClientIP } else { $null }
                UserAgent = if ($auditData) { $auditData.UserAgent } else { $null }
                Workload = if ($auditData) { $auditData.Workload } else { $null }
            }
        } catch {
            Write-Host "Error processing record $($result.Identity): $($_.Exception.Message)" -ForegroundColor Red
        }
    }
    
    try {
        $exportData | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
        Write-Host "Successfully exported to: $OutputPath" -ForegroundColor Green
    } catch {
        Write-Host "Error exporting to CSV: $($_.Exception.Message)" -ForegroundColor Red
    }
}

# Main execution logic
Write-Host "=== Purview Audit Export Script ===" -ForegroundColor Magenta
Write-Host "Generated by PAX (Purview Audit eXporter)" -ForegroundColor Magenta

# These variables will be replaced by the app with actual values
$startDate = "{{START_DATE}}"
$endDate = "{{END_DATE}}"
$authMode = "{{AUTH_MODE}}"
$activityTypes = @({{ACTIVITY_TYPES}})
$outputFile = "{{OUTPUT_FILE}}"
$blockHours = {{BLOCK_HOURS}}
$resultSize = {{RESULT_SIZE}}

Write-Host "Configuration:" -ForegroundColor Cyan
Write-Host "  Start Date: $startDate" -ForegroundColor White
Write-Host "  End Date: $endDate" -ForegroundColor White
Write-Host "  Auth Mode: $authMode" -ForegroundColor White
Write-Host "  Output File: $outputFile" -ForegroundColor White
Write-Host "  Activity Types: $($activityTypes -join ', ')" -ForegroundColor White

# Connect to Purview
if (-not (Connect-ToPurview -AuthMode $authMode)) {
    Write-Host "Failed to connect to Purview. Exiting." -ForegroundColor Red
    exit 1
}

# Search audit logs
$results = Search-AuditLogs -StartDate $startDate -EndDate $endDate -ActivityTypes $activityTypes -ResultSize $resultSize

# Export results
Export-ToCsv -Results $results -OutputPath $outputFile

# Disconnect
try {
    Disconnect-ExchangeOnline -Confirm:$false -ErrorAction SilentlyContinue
    Write-Host "Disconnected from Exchange Online" -ForegroundColor Green
} catch {
    # Ignore disconnect errors
}

Write-Host "=== Export Complete ===" -ForegroundColor Magenta
Write-Host "Total records exported: $($results.Count)" -ForegroundColor Green
Write-Host "Output file: $outputFile" -ForegroundColor Green